# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  
  $('.show-food').on 'click', (event) ->
    event.preventDefault()
    $('#foodModal').modal 'show'
    return
    
  return

# ---
# generated by js2coffee 2.0.3